[profile.default]
src = 'src'
out = 'out'
libs = ['lib']

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

solc = "0.8.19"

# optimizer settings for debugging
# via_ir = false
# optimizer = false
# optimizer_runs = 0
# optimizer_steps = 0

# optimizer settings for snapshotting.
optimizer = true
optimizer_runs = 1000000

bytecode_hash = "none"
cbor_metadata = false

# Build metadata used for testing rain meta aware contracts in this folder rather
# than expose ffi to forge.
fs_permissions = [
  { access = "read", path = "./meta"}, {access = "read", path = "./lib/rain.interpreter/meta/RainterpreterExpressionDeployerNPE2.rain.meta"},
  { access = "read", path = "./lib/rain.interpreter/deployments/latest/RainterpreterParserNPE2" },
  { access = "read", path = "./lib/rain.interpreter/deployments/latest/RainterpreterStoreNPE2" },
  { access = "read", path = "./lib/rain.interpreter/deployments/latest/RainterpreterNPE2" },
  { access = "read", path = "./lib/rain.interpreter/deployments/latest/RainterpreterExpressionDeployerNPE2" },
  { access = "read-write", path = "./meta/OrderBookSubParserAuthoringMeta.rain.meta"}
]

remappings = [
  "rain.interpreter/=lib/rain.interpreter/src/",
  "rain.metadata/=lib/rain.metadata/src/"
]

[fuzz]
runs = 5096