version = 1

[[annotations]]
path = [
    ".envrc",
    ".gas-snapshot",
    ".github/**/",
    ".gitignore",
    ".gitmodules",
    ".vscode/**/",
    ".cargo/**/",
    "README.md",
    "AGENTS.md",
    "CLAUDE.md",
    "flake.lock",
    "flake.nix",
    "foundry.toml",
    "foundry.lock",
    "slither.config.json",
    "typeshare.toml",
    "REUSE.toml",
    "pointers.sh",
    "prep-tauri.sh",
    "package.json",
    "package-lock.json",
    "Cargo.lock",
    "Cargo.toml",
    ".devcontainer.json",
    ".env.example",
    "tauri-app/.env.example",
    "prep-all.sh",
    "packages/**/",
    "ai_commands/**/",
    "subgraph/**/",
    "crates/**/",
    "tauri-app/**/",
    "test-resources/**/",
]
SPDX-FileCopyrightText = "Copyright (c) 2020 Rain Open Source Software Ltd"
SPDX-License-Identifier = "LicenseRef-DCL-1.0"
